### ISSUE TITLE
HMAC SHA256 hashing

### ISSUE THREAD

**Issue by markpatterson27** [arduino-libraries/ArduinoECCX08#42]
According to the [datasheet](https://docs.arduino.cc/resources/datasheets/ATECC508A-datasheet.pdf), the ECC508 can do HMAC hashing but I don't see it implemented in this library. Is it possible to do HMAC-SHA256 hashing with this library?

**Comment by RLeclair** [comment]
I'm interested as well in this, I am investigating a way to implement this, is there already work being done?

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino-libraries/ArduinoECCX08/pull/45
