### ISSUE TITLE
[Question] secure boot

### ISSUE THREAD

**Issue by Mathteus** [arduino-libraries/ArduinoECCX08#44]
is it possible to use this library to make secure boot?
I'm using an ESP32 Wrover Module, with the ATECC608B chip.

**Comment by per1234** [comment]
Hi @Mathteus. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
