### ISSUE TITLE
Wire lib error

### ISSUE THREAD

**Issue by IwantMicroBitToWork** [arduino-libraries/ArduinoECCX08#48]
Im getting this error message:
\Documents\Arduino\libraries\Wire\src\Wire.cpp:33:33: fatal error: esp32-hal-i2c-slave.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by per1234** [comment]
Hi @IwantMicroBitToWork. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
