### ISSUE TITLE
How to use ATECC608A with SIMCOM7600?

### ISSUE THREAD

**Issue by ALEXANDERSSONN** [arduino-libraries/ArduinoECCX08#67]
I would like to know if the ECC608 and SIMCOM7600 can be used together. I intend to use a certificate from the ECC608 and have the SIMCOM7600 communicate with AWS IoT Core via MQTT(S), with the board I’m using being the Arduino MKR ZERO.

I tried to read the Private Key but was unable to do so because the ECC608 stores the Private Key.

AWS iot core MQTT(S) need a Private Key but i can't read Private Key from ECC608.

**Comment by per1234** [comment]
Hi @ALEXANDERSSONN. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
